version: '2'
services:
    edm-app:
        image: edm
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://edm-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=EDM
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://edm-elasticsearch:9200
        ports:
            - 8080:8080
    edm-mongodb:
        extends:
            file: mongodb.yml
            service: edm-mongodb
    edm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: edm-elasticsearch
